---
# tasks file for sap-preconfigure configuration

- import_tasks: 2772999/02-configure-selinux.yml
  when: sap_preconfigure_config_all is undefined or sap_preconfigure_config_all or (sap_preconfigure_2772999_02 is defined and sap_preconfigure_2772999_02)

- import_tasks: 2772999/03-configure-hostname.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_03 is defined and sap_preconfigure_2772999_03)

- import_tasks: 2772999/04-configure-network-time-and-date.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_04 is defined and sap_preconfigure_2772999_04)

- import_tasks: 2772999/05-configure-firewall.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_05 is defined and sap_preconfigure_2772999_05)

- import_tasks: 2772999/06-configure-uuidd.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_06 is defined and sap_preconfigure_2772999_06)

- import_tasks: 2772999/07-configure-tmpfs.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_07 is defined and sap_preconfigure_2772999_07)

- import_tasks: 2772999/08-configure-linux-kernel-parameters.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_08 is defined and sap_preconfigure_2772999_08)

- import_tasks: 2772999/09-configure-process-resource-limits.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_09 is defined and sap_preconfigure_2772999_09)

- import_tasks: 2772999/10-configure-systemd-tmpfiles.yml
  when: sap_preconfigure_config_all is undefined and sap_preconfigure_config_all or (sap_preconfigure_2772999_10 is defined and sap_preconfigure_2772999_10)

...
