---

- name: list of required SAP Notes
  debug:
    var: __sap_preconfigure_sapnotes | difference([''])

- name: include configuration actions for required sapnotes
  include_tasks: "sapnote/{{ item }}.yml"
  with_items: "{{ __sap_preconfigure_sapnotes | difference(['']) }}"
#- include: "{{ './' + ansible_distribution + ansible_distribution_major_version + '/recommendations.yml' }}"

...
