---
# tasks file for sap-preconfigure: installation

- import_tasks: sapnote/2772999/01-install-additional-software-packages-sap.yml
  tags:
    - 'role::sap-preconfigure'
    - 'role::sap-preconfigure:install'
    - 'role::sap-preconfigure:install:2772999:01-install-additional-software-packages-sap'
