---

- name: Configure 2772999-4
  debug:
    msg: "SAP note 2772999 Step 4: Configure Network Time and Date"

- name: Start and enable service chronyd
  systemd:
    name: chronyd
    state: started
    enabled: yes
