---

- name: Assert 2772999-7
  debug:
    msg: "SAP note 2772999 Step 7: Configure tmpfs;
    memtotal_mb = {{ ansible_memtotal_mb }};
    swaptotal_mb = {{ ansible_swaptotal_mb }};
    sap_preconfigure_size_of_tmpfs_gb = {{ sap_preconfigure_size_of_tmpfs_gb }}"

- import_tasks: ../../RedHat/generic/assert-tmpfs.yml
