---
# tasks file for prep-sap-install: configuration

# 07-configure-tmpfs.yml
  - debug:
      msg: "SAP note 2772999 Step 7: Configure tmpfs; memtotal_mb = {{ ansible_memtotal_mb }}; swaptotal_mb = {{ ansible_swaptotal_mb }}; prep_sap_install_size_of_tmpfs_gb = {{ prep_sap_install_size_of_tmpfs_gb }}"
  - name: "Check and configure the size of tmpfs"
    lineinfile:
      path: /etc/fstab
      regexp: '/dev/shm'
      line: "none     /dev/shm       tmpfs   defaults,size={{ prep_sap_install_size_of_tmpfs_gb }}G        0 0"
      state: present

  - name: "grep /dev/shm /etc/fstab"
    command: bash -lc "grep /dev/shm /etc/fstab"
    register: shell_result
  - debug:
      var: shell_result.stdout_lines, shell_result.stderr_lines

  - name: "mount -o remount /dev/shm"
    command: bash -lc "mount -o remount /dev/shm"
    register: shell_result
  - debug:
      var: shell_result.stdout_lines, shell_result.stderr_lines

  - name: "df -k /dev/shm"
    command: bash -lc "df -k /dev/shm"
    register: shell_result
  - debug:
      var: shell_result.stdout_lines, shell_result.stderr_lines
