---
# tasks file for prep-sap-install: configuration

# 09-configure-process-resource-limits.yml
  - debug:
      msg: "SAP note 2772999 Step 9: Configure Process Resource Limits"
  - name: "Create file /etc/security/limits.d/99-sap.conf if it does not exist"
    file:
      path: /etc/security/limits.d/99-sap.conf
      state: touch
      mode: 0644

  - name: "Set soft limit for nproc to unlimited for group sapsys"
    lineinfile:
      path: /etc/security/limits.d/99-sap.conf
      line: "@sapsys    soft    nproc    unlimited"
      state: present
