---

- name: Configure 2002167-2a
  debug:
    msg: "SAP note 2002167 Step 2a: Configure the Firewall"

- import_tasks: ../../RedHat/generic/configure-firewall.yml

- name: Configure 2002167-2b
  debug:
    msg: "SAP note 2002167 Step 2b: Configure SELinux"

- import_tasks: ../../RedHat/generic/configure-selinux.yml
