---

- name: Configure 2002167-3
  debug:
    msg: "SAP note 2002167 Step 3: Setting the Hostname"

- import_tasks: ../../RedHat/generic/configure-hostname.yml
- import_tasks: ../../RedHat/generic/configure-etc-hosts.yml
- import_tasks: ../../RedHat/generic/check-dns-name-resolution.yml
