---
# tasks file for sap-preconfigure: configuration

# 06-additional-notes-for-installing-sap-systems.yml
- debug:
    msg: "SAP note 2002167 Step 6: Additional notes for installing SAP systems"

- name: Link LDAP library libldap
  file:
    src: /usr/lib64/libldap-2.3.so.0
    dest: /usr/lib64/libldap.so.199
    state: link

- name: Link LDAP library liblber
  file:
    src: /usr/lib64/liblber-2.3.so.0
    dest: /usr/lib64/liblber.so.199
    state: link

- name: Test if file /usr/lib/tmpfiles.d/sap.conf exists
  stat:
    path: /usr/lib/tmpfiles.d/sap.conf
  register: systemd_sap_conf
  failed_when: no

- debug:
    var: systemd_sap_conf.stat.exists

- name: Copy file /etc/tmpfiles.d/sap.conf if necessary
  copy:
    src: etc/tmpfiles.d/sap.conf
    dest: /etc/tmpfiles.d/sap.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: not systemd_sap_conf.stat.exists

...
