---

- debug:
    msg: "imported RedHat/generic/assert-tmpfs.yml"

- name: Check the size of tmpfs
#  command: awk '/\/dev\/shm/&&/tmpfs/&&/{{ sap_preconfigure_size_of_tmpfs_gb }}G/{gsub ("defaults,size=", "", $4); print $4}' /etc/fstab
  command: awk '/\/dev\/shm/&&/tmpfs/{gsub ("defaults,size=", "", $4); print $4}' /etc/fstab
  register: __fstab_tmpfs_size_result
  ignore_errors: yes
  changed_when: no

- name: Assert that there is an entry for tmpfs in /etc/fstab
  assert:
    that: __fstab_tmpfs_size_result.stdout != ''
    fail_msg: "FAIL: There is no entry for 'tmpfs' in /etc/fstab!"
    success_msg: "PASS: An entry for 'tmpfs' in /etc/fstab exists."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

- name: Assert that the size of tmpfs is large enough as per /etc/fstab
  assert:
    that: "'{{ sap_preconfigure_size_of_tmpfs_gb }}G' in __fstab_tmpfs_size_result.stdout"
    fail_msg: "FAIL: The size of tmpfs in /etc/fstab is '{{ __fstab_tmpfs_size_result.stdout }}' but the expected size is '{{ sap_preconfigure_size_of_tmpfs_gb }}G!"
    success_msg: "PASS: The size of tmpfs in /etc/fstab is '{{ __fstab_tmpfs_size_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"
  when: __fstab_tmpfs_size_result.stdout != ''

- name: Check if /dev/shm is available and has the expected size
  shell: df -hl /dev/shm | awk '/\/dev\/shm/&&/tmpfs/{print $2}'
  register: __df_shm_result
  ignore_errors: yes
  changed_when: no

- name: Assert that the current size of tmpfs is large enough as per df output
  assert:
    that: "__df_shm_result.stdout == '{{ sap_preconfigure_size_of_tmpfs_gb }}G'"
    fail_msg: "FAIL: The current size of tmpfs is '{{ __df_shm_result.stdout }}' but the expected size is '{{ sap_preconfigure_size_of_tmpfs_gb }}G!"
    success_msg: "PASS: The current size of tmpfs is '{{ __df_shm_result.stdout }}'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
