---

- debug:
    msg: "imported RedHat/generic/assert-hostname.yml"

- name: Check if hostname is set
  command: hostname
  register: __sap_preconfigure_register_hostname_assert
  ignore_errors: yes
  changed_when: no

- name: Assert that the output of hostname matches the content of variable sap_hostname
  assert:
    that: "__sap_preconfigure_register_hostname_assert.stdout == '{{ sap_hostname }}'"
    fail_msg: "FAIL: The output of 'hostname' does not match the content of variable 'sap_hostname'!"
    success_msg: "PASS: The output of 'hostname' matches the content of variable 'sap_hostname'."
  ignore_errors: "{{ sap_preconfigure_assert_ignore_errors|d(false) }}"

...
