---

- debug:
    msg: "imported RedHat/generic/configure-process-resource-limits.yml"

- name: Set the hard and soft limit for the max number of open files per process (nofile) to 65536 for group 'sapsys'
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    create: yes
    regexp: '^@sapsys\s+{{ line_item }}\s+nofile\s.*'
    line: "@sapsys\t{{ line_item }}\tnofile\t65536"
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item

- name: Set the hard and soft limit for the max number of open files per process (nofile) to 65536 for group '{{ sap_preconfigure_db_group_name }}'
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    create: yes
    regexp: '^@{{ sap_preconfigure_db_group_name }}\s+{{ line_item }}\s+nofile\s.*'
    line: "@{{ sap_preconfigure_db_group_name }}\t{{ line_item }}\tnofile\t65536"
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item
  when:
    - sap_preconfigure_db_group_name is defined

- name: Set the hard and soft limit for the max number of processes per user (nproc) to unlimited for group 'sapsys'
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    create: yes
    regexp: '^@sapsys\s+{{ line_item }}\s+nproc\s.*'
    line: "@sapsys\t{{ line_item }}\tnproc\tunlimited"
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item

- name: Set the hard and soft limit for the max number of processes per user (nproc) to unlimited for group '{{ sap_preconfigure_db_group_name }}'
  lineinfile:
    path: /etc/security/limits.d/99-sap.conf
    create: yes
    regexp: '^@{{ sap_preconfigure_db_group_name }}\s+{{ line_item }}\s+nproc\s.*'
    line: "@{{ sap_preconfigure_db_group_name }}\t{{ line_item }}\tnproc\tunlimited"
  with_items:
    - hard
    - soft
  loop_control:
    loop_var: line_item
  when:
    - sap_preconfigure_db_group_name is defined
