---

- debug:
    msg: "imported RedHat/generic/configure-hostname.yml"

- debug:
    msg:
      - "sap_hostname = {{ sap_hostname }}"

# The hostname module fails if it is run from an initrc_t context
# See also: https://github.com/ansible/ansible/issues/19814
# The following applies an appropriate selinux rule if the role is run in initrc_t context
- name: Get current SELinux context
  command: "id -Z"
  register: sap_base_settings_register_selinux_context
  changed_when: false
  ignore_errors: true

- name: Debug current SELinux context
  debug:
    msg: "The current SELinux context is {{ sap_base_settings_register_selinux_context.stdout.split(':')[2] }} "
  ignore_errors: true

- name: Adding SELinux rule so that hostname will work from initrc_t context
  block:
    - name: copy SELinux Rule
      copy:
        src=tmp/hostnamectl-fix.pp
        dest=/tmp/hostnamectl-fix.pp
    - name: apply SELinux Rule
      command: semodule -i /tmp/hostnamectl-fix.pp
  when: sap_base_settings_register_selinux_context.stdout.split(':')[2] is defined and sap_base_settings_register_selinux_context.stdout.split(':')[2] == 'initrc_t'

- name: Ensure short system hostname is set
  hostname:
    name: "{{ sap_hostname }}"

...
