---

- debug:
    msg: "imported RedHat/generic/configure-hostname.yml"

# The hostname module fails if it is run from an initrd_t context
# See also: https://github.com/ansible/ansible/issues/19814
# The following applies an appropriate selinux rule if the role is run in initrd_t context
- name: Get current SE Linux context
  command: "id -Z"
  register: sap_base_settings_register_selinux_context
  changed_when: false
  ignore_errors: true

- name: Debug current SE Linux context
  debug:
    msg: "the current context is {{ sap_base_settings_register_selinux_context.stdout.split(':')[2] }} "
  ignore_errors: true

- name: Adding SE Linux rule so that hostname will work from initrd_t context
  block:
    - name: copy SE Linux Rule
      copy:
        src=hostnamectl-fix.pp
        dest=/root/hostnamectl-fix.pp
    - name: apply SE Linux Rule
      command: semodule -i /root/hostnamectl-fix.pp
  when: sap_base_settings_register_selinux_context.stdout.split(':')[2] is defined and sap_base_settings_register_selinux_context.stdout.split(':')[2] == 'initrc_t'

- name: ensure short system hostname is set
  hostname:
    name: '{{ sap_hostname }}'

...
