---

- debug:
    msg: "imported RedHat/generic/configure-etc-hosts.yml"

- name: get all hostaliases of {{ sap_ip }}
  shell: |
    awk ' ( $1 == "{{ sap_ip }}" ) {
      for (i=2; i<=NF; ++i) { 
        if (( $i != "{{ sap_hostname }}" ) && ( $i != "{{ sap_hostname }}.{{ sap_domain }}" )) { printf $i" " } 
      } 
    }' /etc/hosts
  register: sap_base_settings_register_hostname_aliases
  changed_when: false

- name: print aliases
  debug:
    var=sap_hostname_aliases

- name: ensure hostentry is correct
  lineinfile:
    path: /etc/hosts
    regexp: '^{{ sap_ip }}\s'
          line: '{{ sap_ip }} {{ sap_hostname }}.{{ sap_domain }} {{ sap_hostname }} {{ sap_base_settings_register_hostname_aliases.stdout }}'

- name: check for double entries of {{ sap_ip }} in /etc/hosts
  shell: |
    n=$(grep "^{{ sap_ip }}\s" /etc/hosts | wc -l)
    if [ $n -eq 1 ]; then
      exit 0
    else
      echo "Duplicate IP Entry in /etc/hosts"
      exit 1
    fi
  changed_when: false

- name: check for double entries of hostnames in /etc/hosts
  shell: |
    n=$(grep -w "{{ item }}" /etc/hosts | wc -l)
    if [ $n -eq 1 ]; then
      exit 0
    else
      exit 1
    fi
  with_items:
    - '{{ sap_hostname }}.{{ sap_domain }}'
    - '{{ sap_hostname }}'
  changed_when: false

- name: check hostname settings
  shell: test "$(hostname -s)" = "$(hostname)" -a "$(hostname -f)" = "$(hostname).$(hostname -d)"
  changed_when: false

...
