---

- debug:
    msg: "imported RedHat/generic/configure-selinux.yml"

- name: Set SELinux state
  selinux:
    state: "{{ sap_preconfigure_selinux_state }}"
    policy: targeted
  register: __sap_preconfigure_register_selinux_state

- name: Call Reboot handler if necessary
  command: /bin/true
  notify: __sap_preconfigure_reboot_handler
  when: __sap_preconfigure_register_selinux_state.reboot_required
