---
# tasks file for sap-preconfigure: configuration

- debug:
    msg: "imported RedHat/generic/configure-systemd-tmpfiles.yml"

- name: Test if file /usr/lib/tmpfiles.d/sap.conf exists
  stat:
    path: /usr/lib/tmpfiles.d/sap.conf
  register: systemd_sap_conf
  failed_when: no

- debug:
    var: systemd_sap_conf.stat.exists

- name: Copy file /etc/tmpfiles.d/sap.conf if necessary
  copy:
    src: etc/tmpfiles.d/sap.conf
    dest: /etc/tmpfiles.d/sap.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  when: not systemd_sap_conf.stat.exists

...
